baseURL = "https://marloanzarut123.github.io/css_website/"
title = "Project Title"
description = "This is a project description"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Elinor Funk", "Leland Whitlock", "Marlo Anzarut"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://marloanzarut123.github.io/css_website/"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

